
// Java program using map() function
import java.io.*;
import java.util.*;
import java.util.stream.Collectors;

class FlatDiffMapStream {

    public static void main(String[] args) {
        // making the array list object
        // ArrayList<String> lang = new ArrayList<>();
        // lang.add("Java");
        // lang.add("Swift");
        // lang.add("Python");
        // lang.add("Go");
        // System.out.println("List of languages ----->>>>> " + lang);

        // // lets use map() to convert list of fruit
        // List list = lang.stream()
        //         .map(s -> s.length())
        //         .collect(Collectors.toList());
        // System.out.println("List generated by map-" + list);

        ArrayList<Integer> lang = new ArrayList<>();
        lang.add(34);
        lang.add(87);
        lang.add(78);
        lang.add(45);
        System.out.println("List of languages ----->>>>> " + lang);

        // lets use map() to convert list of fruit
        List list = lang.stream()
                .map(s -> s)
                .collect(Collectors.toList());
        System.out.println("List generated by map-" + list);


        List<List<Integer> > number = new ArrayList<>();

        // adding the elements to number arraylist
        number.add(Arrays.asList(23, 21));
        number.add(Arrays.asList(43, 48));
        number.add(Arrays.asList(54, 61));
        number.add(Arrays.asList(72, 88));
        
        System.out.println("List of list-" + number);
        
        // using flatmap() to flatten this list
        List<Integer> flatList
            = number.stream()
                    .flatMap(l -> l.stream())
                    .collect(Collectors.toList());

        System.out.println("List generate by flatMap: "+ flatList);
    }
}
